### ISSUE TITLE
Issues with Core Coder

### ISSUE THREAD

**Issue by NiewNie** [CoreCoder-Devs/core-coder#11]
Can someone please help me with this error?
Error: ENOENT: no such file or directory, mkdir 'C:\Users\NiewNie\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState/games/com.mojang\development_resource_packs\' at mkdirSync (fs.js:845:3) at Object.fs.mkdirSync (electron/js2c/asar.js:718:16) at listFiles (file:///C:/Users/NiewNie/Downloads/cc-1.5-win64/resources/app/src/home.js:91:12) at refreshRPMap (file:///C:/Users/NiewNie/Downloads/cc-1.5-win64/resources/app/src/home.js:308:21) at refreshProjectMap (file:///C:/Users/NiewNie/Downloads/cc-1.5-win64/resources/app/src/home.js:106:5) at init (file:///C:/Users/NiewNie/Downloads/cc-1.5-win64/resources/app/src/home.js:510:5) at file:///C:/Users/NiewNie/Downloads/cc-1.5-win64/resources/app/src/home.html:307:21

**Comment by skybird23333** [comment]
Hey, sorry for the late reply. Do you have Minecraft Bedrock installed on your Computer?

**Comment by Hanprogramer** [comment]
This issue should be fixed in v1.5.1 patch

**Comment by skybird23333** [comment]
We already have it, its gonna be v1.5.2
