### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by Mat384** [CoreCoder-Devs/core-coder#12]
I tried to make a new project and this error appeared
TypeError: Cannot read property 'style' of null at createProject (file:///C:/Users/matya/Downloads/cc-1.5.1/resources/app/src/home.js:503:11) at HTMLButtonElement. (file:///C:/Users/matya/Downloads/cc-1.5.1/resources/app/src/scripts/string_validator.js:142:13)
![image](https://user-images.githubusercontent.com/75716177/101589436-2184e500-3a34-11eb-9283-eb8b6deb5803.png)

**Comment by skybird23333** [comment]
This will be patched in the next build. For now hit ctrl + r every time you create one and you should see the created project in your list.
